### ISSUE TITLE
matmul benchmark not running

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#183]
o4bc-bench benchmark run matmul_benchmark
Running "matmul_benchmark" setup commands
$ python3 -m venv .venv
(venv) $ ./setup.sh
Requirement already satisfied: numpy in ./.venv/lib/python3.6/site-packages (from -r ./requirements.txt (line 1))
Collecting tensorflow-gpu (from -r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/76/04/43153bfdfcf6c9a4c38ecdb971ca9a75b9a791bb69a764d652c359aca504/tensorflow_gpu-1.14.0-cp36-cp36m-manylinux1_x86_64.whl
⠼ matmul_benchmark(setup): ./setup.sh
⠸ matmul_benchmark(setup): ./setup.sh
Collecting gast>=0.2.0 (from tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/5f/1c/b59500a88c5c3d9d601c5ca62b9df5e0964764472faed82a182958a922c5/gast-0.5.3-py3-none-any.whl
Collecting google-pasta>=0.1.6 (from tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/a3/de/c648ef6835192e6e2cc03f40b19eeda4382c49b5bafb43d88b931c4c74ac/google_pasta-0.2.0-py3-none-any.whl
Collecting absl-py>=0.7.0 (from tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/2c/03/e3e19d3faf430ede32e41221b294e37952e06acc96781c417ac25d4a0324/absl_py-1.0.0-py3-none-any.whl
Collecting astor>=0.6.0 (from tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/c3/88/97eef84f48fa04fbd6750e62dcceafba6c63c81b7ac1420856c8dcc0a3f9/astor-0.8.1-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10.0 in ./.venv/lib/python3.6/site-packages (from tensorflow-gpu->-r ./requirements.txt (line 2))
Requirement already satisfied: protobuf>=3.6.1 in ./.venv/lib/python3.6/site-packages (from tensorflow-gpu->-r ./requirements.txt (line 2))
Collecting keras-preprocessing>=1.0.5 (from tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/79/4c/7c3275a01e12ef9368a892926ab932b33bb13d55794881e3573482b378a7/Keras_Preprocessing-1.1.2-py2.py3-none-any.whl
Requirement already satisfied: wheel>=0.26 in ./.venv/lib/python3.6/site-packages (from tensorflow-gpu->-r ./requirements.txt (line 2))
Collecting termcolor>=1.1.0 (from tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Collecting wrapt>=1.11.1 (from tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ba/8c/3d3dff02ae905157ba417b801f4a7aa4e6fedbc43882e9c765b7aae438ac/wrapt-1.14.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Collecting grpcio>=1.8.6 (from tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/65/75/8b706e1170e2c7b6242b1675259e47986bb4fc490f29387989a965972e6e/grpcio-1.44.0.tar.gz
Collecting tensorboard<1.15.0,>=1.14.0 (from tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/91/2d/2ed263449a078cd9c8a9ba50ebd50123adf1f8cfbea1492f9084169b89d9/tensorboard-1.14.0-py3-none-any.whl
Requirement already satisfied: keras-applications>=1.0.6 in ./.venv/lib/python3.6/site-packages (from tensorflow-gpu->-r ./requirements.txt (line 2))
Collecting tensorflow-estimator<1.15.0rc0,>=1.14.0rc0 (from tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/3c/d5/21860a5b11caf0678fbc8319341b0ae21a07156911132e0e71bffed0510d/tensorflow_estimator-1.14.0-py2.py3-none-any.whl
Collecting werkzeug>=0.11.15 (from tensorboard<1.15.0,>=1.14.0->tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/f4/f3/22afbdb20cc4654b10c98043414a14057cd27fdba9d4ae61cea596000ba2/Werkzeug-2.0.3-py3-none-any.whl
Collecting markdown>=2.6.8 (from tensorboard<1.15.0,>=1.14.0->tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/9f/d4/2c7f83915d437736996b2674300c6c4b578a6f897f34e40f5c04db146719/Markdown-3.3.6-py3-none-any.whl
Requirement already satisfied: setuptools>=41.0.0 in ./.venv/lib/python3.6/site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow-gpu->-r ./requirements.txt (line 2))
Requirement already satisfied: h5py in ./.venv/lib/python3.6/site-packages (from keras-applications>=1.0.6->tensorflow-gpu->-r ./requirements.txt (line 2))
Collecting dataclasses; python_version < "3.7" (from werkzeug>=0.11.15->tensorboard<1.15.0,>=1.14.0->tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fe/ca/75fac5856ab5cfa51bbbcefa250182e50441074fdc3f803f6e76451fab43/dataclasses-0.8-py3-none-any.whl
Collecting importlib-metadata>=4.4; python_version < "3.10" (from markdown>=2.6.8->tensorboard<1.15.0,>=1.14.0->tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/a0/a1/b153a0a4caf7a7e3f15c2cd56c7702e2cf3d89b1b359d1f1c5e59d68f4ce/importlib_metadata-4.8.3-py3-none-any.whl
Requirement already satisfied: cached-property; python_version < "3.8" in ./.venv/lib/python3.6/site-packages (from h5py->keras-applications>=1.0.6->tensorflow-gpu->-r ./requirements.txt (line 2))
Collecting zipp>=0.5 (from importlib-metadata>=4.4; python_version < "3.10"->markdown>=2.6.8->tensorboard<1.15.0,>=1.14.0->tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bd/df/d4a4974a3e3957fd1c1fa3082366d7fff6e428ddb55f074bf64876f8e8ad/zipp-3.6.0-py3-none-any.whl
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata>=4.4; python_version < "3.10"->markdown>=2.6.8->tensorboard<1.15.0,>=1.14.0->tensorflow-gpu->-r ./requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/45/6b/44f7f8f1e110027cf88956b59f2fad776cca7e1704396d043f89effd3a0e/typing_extensions-4.1.1-py3-none-any.whl
Building wheels for collected packages: termcolor, grpcio
  Running setup.py bdist_wheel for termcolor: started
  Running setup.py bdist_wheel for termcolor: finished with status 'done'
  Stored in directory: /home/legger/.cache/pip/wheels/7c/06/54/bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6
  Running setup.py bdist_wheel for grpcio: started
  Running setup.py bdist_wheel for grpcio: still running...
  Running setup.py bdist_wheel for grpcio: still running...
  Running setup.py bdist_wheel for grpcio: still running...
  Running setup.py bdist_wheel for grpcio: still running...
  Running setup.py bdist_wheel for grpcio: still running...
  Running setup.py bdist_wheel for grpcio: finished with status 'done'
  Stored in directory: /home/legger/.cache/pip/wheels/1e/60/b5/d8c8372c2015aba94390cfacfe54d1320d6e4a98f81129c1c4
Successfully built termcolor grpcio
Installing collected packages: gast, google-pasta, absl-py, astor, keras-preprocessing, termcolor, wrapt, grpcio, dataclasses, werkzeug, zipp, typing-extensions, importlib-metadata, markdown, tensorboard, tensorflow-estimator, tensorflow-gpu
Successfully installed absl-py-1.0.0 astor-0.8.1 dataclasses-0.8 gast-0.5.3 google-pasta-0.2.0 grpcio-1.44.0 importlib-metadata-4.8.3 keras-preprocessing-1.1.2 markdown-3.3.6 tensorboard-1.14.0 tensorflow-estimator-1.14.0 tensorflow-gpu-1.14.0 termcolor-1.1.0 typing-extensions-4.1.1 werkzeug-2.0.3 wrapt-1.14.0 zipp-3.6.0
Running "matmul_benchmark" preset "matrix_20x30_GPU"
(venv) $ ./matmul_benchmark.py gpu 20 30
/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "./matmul_benchmark.py", line 32, in <module>
    if tf.config.list_physical_devices('GPU') == 0:
  File "/home/legger/OpenForBC-Benchmark/benchmarks/matmul_benchmark/.venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation_wrapper.py", line 106, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.config' has no attribute 'list_physical_devices'
Benchmark "matmul_benchmark" preset "matrix_20x30_GPU" command "./matmul_benchmark.py gpu 20 30" failed
Task (venv) $ ./matmul_benchmark.py gpu 20 30 failed with return code 1
ERROR: Benchmark "matmul_benchmark" failed

**Comment by leggerf** [comment]
same error with python 3.7

**Comment by leggerf** [comment]
works with python 3.9, closing
